apiVersion: tekton.dev/v1beta1
kind: PipelineRun
meta
  generateName: cicd-demo-run-
spec:
  pipelineSpec:
    workspaces:
      - name: shared-workspace
    tasks:
      - name: fetch-repo
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: shared-workspace
        params:
          - name: url
            value: https://github.com/jackyh0/cicd_demo.git
          - name: revision
            value: main
      - name: test
        taskRef:
          name: run-nose-tests
        runAfter: [fetch-repo]
        workspaces:
          - name: source
            workspace: shared-workspace
      - name: cleanup
        taskRef:
          name: cleanup-workspace
        runAfter: [test]
        workspaces:
          - name: source
            workspace: shared-workspace
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: oc-pipelines-console-pvc
