apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: cicd-demo-run-
spec:
  pipelineSpec:
    workspaces:
      - name: shared-workspace
    tasks:
      - name: fetch-repo
        taskSpec:
          workspaces:
            - name: output
          params:
            - name: url
              type: string
            - name: revision
              type: string
              default: "main"
          steps:
            - name: clone
              image: alpine/git
              # ⚠️ NO securityContext — let OpenShift auto-assign
              workingDir: $(workspaces.output.path)
              script: |
                git clone $(params.url) .
                git checkout $(params.revision)
        workspaces:
          - name: output
            workspace: shared-workspace
        params:
          - name: url
            value: https://github.com/jackyh0/cicd_demo.git
          - name: revision
            value: main

      - name: test
        taskRef:
          name: run-pytest-tests
        runAfter: [fetch-repo]
        workspaces:
          - name: source
            workspace: shared-workspace

      - name: cleanup
        taskRef:
          name: cleanup-workspace
        runAfter: [test]
        workspaces:
          - name: source
            workspace: shared-workspace

  workspaces:
    - name: shared-workspace
      emptyDir: {}