apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oc-pipelines-console-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: skills-network-learner   # ✅ allowed
  resources:
    requests:
      storage: 1Gi